= Crossvale customizable AMQ 72-1.3.GA broker templates

IMPORTANT: This is a _vendor branch_ and *SHOULD NOT* be merged into any other
           branch that matches an upstream branch.

This branch tracks Crossvale-specific modifications to the Red Hat AMQ
OpenShift templates to support customization of the _broker.xml_ Artemis
configuration file.

Client-specific modifications should reside in their own sub-branches.

The customization path is as defined in
https://access.redhat.com/solutions/4426521[Deploying AMQ 7 Broker with a Custom Broker Configuration Using Templates].

Certain customizations are not necessary (they are handled "automatically" by
the upstream _launch.sh_ Docker ENTRYPOINT for the AMQ broker containers);
refer to the appropriate version (tag) of _launch.sh_ in the upstream
https://github.com/jboss-container-images/jboss-amq-7-broker-openshift-image[jboss-container-images/jboss-amq-7-broker-openshift-image]
repository for details.

It is strongly recommended that client deployments use a *tagged* commit
corresponding to the appropriate upstream tag when installing templates.
(For example, the initial set of FHB-specific modifications against Red Hat tag
_72-1.3.GA_ exist in the the _72-1.3.GA-FHB-0_ tag in this repository.)

NOTE: Original (upstream) README content follows.

---
# Red Hat AMQ 7.2.4 OpenShift container image

NOTE: Extends link:https://github.com/jboss-container-images/jboss-amq-7-broker-image[Red Hat AMQ 7.2.4 container image]

# License

See link:LICENSE[LICENSE] file.

## Deploying to minishift

First you want to install minishift https://docs.openshift.org/latest/minishift/getting-started/installing.html.  Start it up and set the environment
```
$ minishift start
$ eval $(minishift oc-env)
$ eval $(minishift docker-env)
$ oc login #developer
```
Using Cekit build the image http://concreate.readthedocs.io/en/develop/
```
$ concreate build
```
Deploy the project. 
```
$ oc new-project broker
$ oc create -n broker -f amq-broker-7-image-streams.yaml
$ oc process -n broker -f templates/amq-broker-72-basic.yaml -p APPLICATION_NAME=broker-app -p AMQ_USER=<username> -p AMQ_PASSWORD=<amqpassword>  | oc create -n broker -f -
```
Push the image.  You will need the ip address of openshifts docker registry.  You can get this from the image stream in the openshift console
```
$ docker login -u developer -p $(oc whoami -t) openshift-docker-ip:5000
$ docker tag amq-broker-7/amq-broker-72-openshift:latest openshift-docker-ip:5000/broker/amq-broker-72-openshift:1.3
$ docker push openshift-docker-ip:5000/broker/amq-broker-72-openshift:1.3
```
